### ISSUE TITLE
Develop Course Page

### ISSUE THREAD

**Issue by cmulay** [PH-DC/edu-helper#5]
What to include in this page:
        1. What is diploma
        2. Course Span and Basic Semester Structure
        ---
        1. View Syllabus
        2. View Previous Year's Question Papers
        3. View Previous Year's Model Answer Papers
        4. Other resources

**Comment by ypratham** [comment]
I am interested in doing this one too.

**Comment by cmulay** [comment]
Great ! proceed ahead with the development.

**Comment by cmulay** [comment]
You both can contribute, go ahead !
